#!/usr/bin/perl

# A test script for interaction with the Munin::Protocol parser.

# Currently limited to parsing requests from master to node, and emits
# a "parse error", or responding the parsed line.
#
# Todo:
#
# Print protocol state
#
# Parse requests and responses.

use strict;
use warnings;
use Munin::Protocol;
use IO::Prompter;
use Data::Printer;
use feature 'say';

my $protocol = Munin::Protocol->new();

PROMPT:
while ( prompt 'munin> ' ) {
    next PROMPT if $_ eq '';
    if ( my $r = $protocol->parse_request($_) ) {
        say $r;
    }
    else {
        print STDERR "error: parse error\n";
    }
}
